// <auto-generated />
using System;
using FlightTracker.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightTracker.Backend.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260209234844_AddTrueTrack")]
    partial class AddTrueTrack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FlightTracker.Backend.Models.AircraftImportState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ImportedRows")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastImportedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SourceLastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AircraftImportStates");
                });

            modelBuilder.Entity("FlightTracker.Backend.Models.AircraftMetadata", b =>
                {
                    b.Property<string>("Icao24")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorIcao")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Registration")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Icao24");

                    b.HasIndex("TypeCode");

                    b.ToTable("AircraftMetadata");
                });

            modelBuilder.Entity("FlightTracker.Backend.Models.AircraftSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlightSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icao24")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InSweden")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TrueTrack")
                        .HasColumnType("REAL");

                    b.Property<double?>("Velocity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FlightSessionId");

                    b.HasIndex("Icao24", "TimestampUtc");

                    b.ToTable("AircraftSnapshots");
                });

            modelBuilder.Entity("FlightTracker.Backend.Models.FlightSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgAltitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnteredSwedenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExitedSwedenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icao24")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LastAltitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("LastInSweden")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSnapshotUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastTrueTrack")
                        .HasColumnType("REAL");

                    b.Property<double?>("LastVelocity")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxAltitude")
                        .HasColumnType("REAL");

                    b.Property<int>("SnapshotCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnteredSwedenUtc");

                    b.HasIndex("Icao24", "IsActive");

                    b.ToTable("FlightSessions");
                });

            modelBuilder.Entity("FlightTracker.Backend.Models.AircraftSnapshot", b =>
                {
                    b.HasOne("FlightTracker.Backend.Models.FlightSession", "FlightSession")
                        .WithMany("Snapshots")
                        .HasForeignKey("FlightSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FlightSession");
                });

            modelBuilder.Entity("FlightTracker.Backend.Models.FlightSession", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
