// <auto-generated />
using System;
using FlightTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlightTracker.Data.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260224190847_AddAirborneSnapshotCountToFlightSessions")]
    partial class AddAirborneSnapshotCountToFlightSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlightTracker.Data.Models.AircraftImportState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("ImportedRows")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastImportedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SourceLastWriteUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.HasKey("Id");

                    b.ToTable("AircraftImportStates");
                });

            modelBuilder.Entity("FlightTracker.Data.Models.AircraftMetadata", b =>
                {
                    b.Property<string>("Icao24")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Country")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OperatorIcao")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Registration")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Icao24");

                    b.HasIndex("TypeCode");

                    b.ToTable("AircraftMetadata");
                });

            modelBuilder.Entity("FlightTracker.Data.Models.AircraftSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Callsign")
                        .HasColumnType("text");

                    b.Property<int?>("FlightSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Icao24")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InSweden")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<bool?>("OnGround")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TrueTrack")
                        .HasColumnType("double precision");

                    b.Property<double?>("Velocity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FlightSessionId");

                    b.HasIndex("Icao24", "TimestampUtc");

                    b.ToTable("AircraftSnapshots");
                });

            modelBuilder.Entity("FlightTracker.Data.Models.FlightSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AirborneSnapshotCount")
                        .HasColumnType("integer");

                    b.Property<double?>("AvgAltitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Callsign")
                        .HasColumnType("text");

                    b.Property<string>("CloseReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EnteredSwedenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExitedSwedenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icao24")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("LastAltitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("LastInSweden")
                        .HasColumnType("boolean");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSnapshotUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LastTrueTrack")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastVelocity")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxAltitude")
                        .HasColumnType("double precision");

                    b.Property<int>("SnapshotCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnteredSwedenUtc");

                    b.HasIndex("Icao24", "IsActive");

                    b.ToTable("FlightSessions");
                });

            modelBuilder.Entity("FlightTracker.Data.Models.AircraftSnapshot", b =>
                {
                    b.HasOne("FlightTracker.Data.Models.FlightSession", "FlightSession")
                        .WithMany("Snapshots")
                        .HasForeignKey("FlightSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FlightSession");
                });

            modelBuilder.Entity("FlightTracker.Data.Models.FlightSession", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
